version: "3"
services:
  postgres:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: zintranet
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - mysql:/var/lib/mysql
volumes:
    mysql: ~